version: '3.9'

networks:
  main:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  aggregator:
    build:
      context: services
      dockerfile: services/aggregator/Dockerfile
    networks:
      - main
    restart: unless-stopped

  api:
    build:
      context: services
      dockerfile: services/api/Dockerfile
    deploy:
      replicas: 3
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${API_PORT}/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped

  chronograf:
    deploy:
      replicas: 0
    image: chronograf:1.10.2-alpine
    networks:
      - main
    ports:
      - ${CHRONOGRAF_PORT}:${CHRONOGRAF_PORT}
    restart: unless-stopped
    volumes:
      - chronograf:/var/lib/chronograf

  cockroach-1:
    command: start --advertise-addr=cockroach-1:26357 --http-addr=cockroach-1:8080 --listen-addr=cockroach-1:26357 --sql-addr=cockroach-1:26257 --insecure --join=cockroach-1:26357,cockroach-2:26357,cockroach-3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8080:8080
      - 26257:26257
    restart: unless-stopped
    volumes:
      - cockroach-1:/data/db

  cockroach-2:
    command: start --advertise-addr=cockroach-2:26357 --http-addr=cockroach-2:8081 --listen-addr=cockroach-2:26357 --sql-addr=cockroach-2:26258 --insecure --join=cockroach-1:26357,cockroach-2:26357,cockroach-3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8081:8081
      - 26258:26258
    restart: unless-stopped
    volumes:
      - cockroach-2:/data/db

  cockroach-3:
    command: start --advertise-addr=cockroach-3:26357 --http-addr=cockroach-3:8082 --listen-addr=cockroach-3:26357 --sql-addr=cockroach-3:26259 --insecure --join=cockroach-1:26357,cockroach-2:26357,cockroach-3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8082:8082
      - 26259:26259
    restart: unless-stopped
    volumes:
      - cockroach-3:/data/db

  consumer:
    build:
      context: services
      dockerfile: services/consumer/Dockerfile
    deploy:
      replicas: 3
    networks:
      - main
    restart: unless-stopped

  grafana:
    build:
      context: grafana
    deploy:
      replicas: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GRAFANA_PORT}/api/health"]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    restart: unless-stopped
    volumes:
      - grafana-etc:/etc/grafana
      - grafana-var-lib:/var/lib/grafana

  haproxy:
    build:
      context: haproxy
    networks:
      - main
    ports:
      - 6100:6100
      - 7100:7100
      - 8404:8404
    restart: unless-stopped

  influx:
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_BUCKET=house
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${INFLUX_PORT}/ping"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: influxdb:2.7.5-alpine
    networks:
      - main
    ports:
      - ${INFLUX_PORT}:${INFLUX_PORT}
    restart: unless-stopped
    volumes:
      - influx:/var/lib/influxdb

  mongo:
    build:
      context: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    networks:
      - main
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo:/data/db

  mongo-express:
    environment:
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    image: mongo-express:1.0.2-20-alpine3.19
    networks:
      - main
    ports:
      - 8881:8081
    restart: unless-stopped

  nakama:
    build:
      context: nakama
    deploy:
      replicas: 0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroach-1:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroach-1:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100  
    networks:
      - main
    ports:
      - 7350:7350
      - 7351:7351
    restart: unless-stopped
    volumes:
      - nakama:/nakama/data

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      - main
    ports: 
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}
    restart: unless-stopped

  node:
    build:
      context: node
    deploy:
      replicas: 0
    networks:
      - main
    restart: unless-stopped

  producer:
    build:
      context: services
      dockerfile: services/producer/Dockerfile
    networks:
      - main
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.49.1
    networks:
      - main
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    restart: unless-stopped

  rabbit-1:
    build:
      context: rabbit
    command: /root/init.sh
    networks:
      - main
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    volumes:
      - rabbit-1:/var/lib/rabbitmq/mnesia

  rabbit-2:
    build:
      context: rabbit
    command: /root/init.sh rabbit-1
    networks:
      - main
    ports:
      - 5673:5672
      - 15673:15672
    restart: unless-stopped
    volumes:
      - rabbit-2:/var/lib/rabbitmq/mnesia

  rabbit-3:
    build:
      context: rabbit
    command: /root/init.sh rabbit-1
    networks:
      - main
    ports:
      - 5674:5672
      - 15674:15672
    restart: unless-stopped
    volumes:
      - rabbit-3:/var/lib/rabbitmq/mnesia

  receiver:
    build:
      context: services
      dockerfile: services/receiver/Dockerfile
    deploy:
      replicas: 3
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${RECEIVER_PORT}/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped

  redis:
    image: redis:7.2.4-alpine3.19
    networks:
      - main
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - redis:/data

  redis-insight:
    image: redislabs/redisinsight:1.14.0
    networks:
      - main
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    restart: unless-stopped
    volumes:
      - redis-insight:/db

  redis-slave:
    command: redis-server --slaveof redis ${REDIS_PORT}
    image: redis:7.2.4-alpine3.19
    networks:
      - main
    ports:
      - 6380:6379
    restart: unless-stopped
    volumes:
      - redis-slave:/data

  statsd-exporter:
    image: prom/statsd-exporter:v0.26.0
    networks:
      - main
    ports:
      - ${STATSD_EXPORTER_PORT}:${STATSD_EXPORTER_PORT}
    restart: unless-stopped

volumes:
  chronograf:
  cockroach-1:
  cockroach-2:
  cockroach-3:
  grafana-etc:
  grafana-var-lib:
  influx:
  mongo:
  nakama:
  postgres:
  rabbit-1:
  rabbit-2:
  rabbit-3:
  redis:
  redis-insight:
  redis-slave:
