version: '3.9'

x-logging:
  &default-logging
  driver: "fluentd"
  options:
    fluentd-address: localhost:${FLUENT_PORT}

networks:

  simple:

services:

  api_1:
    build:
      context: api
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped

  api_2:
    build:
      context: api
    logging: *default-logging
    networks:
      - simple
    ports:
      - 5001:${API_PORT}
    restart: unless-stopped

  chronograf:
    depends_on:
      - influx
    image: chronograf:${CHRONOGRAF_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${CHRONOGRAF_PORT}:${CHRONOGRAF_PORT}
    restart: unless-stopped
    volumes:
      - chronograf:/var/lib/chronograf

  cockroach:
    command: start-single-node --insecure
    image: cockroachdb/cockroach:v${COCKROACH_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${COCKROACH_PORT}:${COCKROACH_PORT}
    restart: unless-stopped
    volumes:
      - cockroach:/data/db

  consumer_1:
    build:
      context: consumer
    logging: *default-logging
    networks:
      - simple
    restart: unless-stopped

  consumer_2:
    build:
      context: consumer
    logging: *default-logging
    networks:
      - simple
    restart: unless-stopped

  fluent:
    build:
      context: fluent
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${FLUENT_PORT}:${FLUENT_PORT}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./fluent/fluent.conf
        target: /fluentd/etc/fluent.conf

  grafana:
    build:
      context: grafana
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    restart: unless-stopped
    volumes:
      - grafana_etc:/etc/grafana
      - grafana_var_lib:/var/lib/grafana

  haproxy:
    image: haproxy:${HAPROXY_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${HAPROXY_PORT}:${HAPROXY_PORT}
      - 9010:9010
      - 9103:9103
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

  influx:
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_BUCKET=house
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
    image: influxdb:${INFLUX_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${INFLUX_PORT}:${INFLUX_PORT}
    restart: unless-stopped
    volumes:
      - influx:/var/lib/influxdb

  kafka:
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.213:${KAFKA_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
    image: bitnami/kafka:${KAFKA_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    restart: unless-stopped

  kafka_ui:
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.0.213:${KAFKA_PORT}
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${KAFKA_UI_PORT}:${KAFKA_UI_PORT}
    restart: unless-stopped

  mongo:
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    image: mongo:${MONGO_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}    
    restart: unless-stopped
    volumes:
      - mongo:/data/db

  mongo_express:
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    restart: unless-stopped

  nginx:
    image: nginx:${NGINX_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v${NODE_EXPORTER_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports: 
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}
    restart: unless-stopped

  node:
    build:
      context: node
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: unless-stopped

  postgres:
    build:
      context: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "psql", "-d", "${POSTGRES_DATABASE}", "-U", "${POSTGRES_USER}", "-c", "select 1"]
      interval: 10s
      timeout: 2s
      retries: 2
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  producer:
    build:
      context: producer
    logging: *default-logging
    networks:
      - simple
    restart: unless-stopped

  prometheus:
    depends_on:
      - haproxy
      - node_exporter
      - rabbit
      - statsd_exporter
    image: prom/prometheus:v${PROMETHEUS_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  rabbit:
    build:
      context: rabbit
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
    restart: unless-stopped

  receiver_1:
    build:
      context: receiver
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${RECEIVER_PORT}:${RECEIVER_PORT}
    restart: unless-stopped

  receiver_2:
    build:
      context: receiver
    logging: *default-logging
    networks:
      - simple
    ports:
      - 7001:${RECEIVER_PORT}
    restart: unless-stopped

  receiver_3:
    build:
      context: receiver
    logging: *default-logging
    networks:
      - simple
    ports:
      - 7002:${RECEIVER_PORT}
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - redis:/data

  redis_insight:
    depends_on:
      - redis
    image: redislabs/redisinsight:${REDIS_INSIGHT_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    restart: unless-stopped
    volumes:
      - redis_insight:/db

  statsd_exporter:
    image: prom/statsd-exporter:v${STATSD_EXPORTER_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${STATSD_EXPORTER_PORT}:${STATSD_EXPORTER_PORT}
    restart: unless-stopped

  zookeeper:
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    logging: *default-logging
    networks:
      - simple
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    restart: unless-stopped

volumes:
  chronograf:
  cockroach:
  elastic:
  grafana_etc:
  grafana_var_lib:
  influx:
  kafka:
  kibana:
  mongo:
  postgres:
  redis:
  redis_insight:
