version: '3.9'

networks:
  main:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  aggregator:
    build:
      context: aggregator
    networks:
      - main
    restart: unless-stopped

  api:
    build:
      context: api
    deploy:
      replicas: 2
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${API_PORT}/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped

  chronograf:
    deploy:
      replicas: 0
    image: chronograf:1.10.2-alpine
    networks:
      - main
    ports:
      - ${CHRONOGRAF_PORT}:${CHRONOGRAF_PORT}
    restart: unless-stopped
    volumes:
      - chronograf:/var/lib/chronograf

  cockroach_1:
    command: start --advertise-addr=cockroach_1:26357 --http-addr=cockroach_1:8080 --listen-addr=cockroach_1:26357 --sql-addr=cockroach_1:26257 --insecure --join=cockroach_1:26357,cockroach_2:26357,cockroach_3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cockroach_1:8080/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8080:8080
      - 26257:26257
    restart: unless-stopped
    volumes:
      - cockroach_1:/data/db

  cockroach_2:
    command: start --advertise-addr=cockroach_2:26357 --http-addr=cockroach_2:8081 --listen-addr=cockroach_2:26357 --sql-addr=cockroach_2:26258 --insecure --join=cockroach_1:26357,cockroach_2:26357,cockroach_3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cockroach_2:8081/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8081:8081
      - 26258:26258
    restart: unless-stopped
    volumes:
      - cockroach_2:/data/db

  cockroach_3:
    command: start --advertise-addr=cockroach_3:26357 --http-addr=cockroach_3:8082 --listen-addr=cockroach_3:26357 --sql-addr=cockroach_3:26259 --insecure --join=cockroach_1:26357,cockroach_2:26357,cockroach_3:26357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cockroach_3:8082/health?ready=1"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: cockroachdb/cockroach:v23.1.13
    networks:
      - main
    ports:
      - 8082:8082
      - 26259:26259
    restart: unless-stopped
    volumes:
      - cockroach_3:/data/db

  consumer:
    build:
      context: consumer
    deploy:
      replicas: 2
    networks:
      - main
    restart: unless-stopped

  grafana:
    build:
      context: grafana
    deploy:
      replicas: 0
    networks:
      - main
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    restart: unless-stopped
    volumes:
      - grafana_etc:/etc/grafana
      - grafana_var_lib:/var/lib/grafana

  haproxy:
    build:
      context: haproxy
    networks:
      - main
    ports:
      - 6100:6100
      - 7100:7100
      - 8404:8404
    restart: unless-stopped

  influx:
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_BUCKET=house
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
    image: influxdb:${INFLUX_VERSION}
    networks:
      - main
    ports:
      - ${INFLUX_PORT}:${INFLUX_PORT}
    restart: unless-stopped
    volumes:
      - influx:/var/lib/influxdb

  mongo:
    deploy:
      replicas: 0
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    image: mongo:${MONGO_VERSION}
    networks:
      - main
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}    
    restart: unless-stopped
    volumes:
      - mongo:/data/db

  mongo_express:
    depends_on:
      - mongo
    deploy:
      replicas: 0
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    networks:
      - main
    ports:
      - 8880:${MONGO_EXPRESS_PORT}
    restart: unless-stopped

  nakama:
    build:
      context: nakama
    deploy:
      replicas: 0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroach_1:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroach_1:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100  
    networks:
      - main
    ports:
      - 7350:7350
      - 7351:7351
    restart: unless-stopped
    volumes:
      - nakama:/nakama/data

  node_exporter:
    image: prom/node-exporter:v${NODE_EXPORTER_VERSION}
    networks:
      - main
    ports: 
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}
    restart: unless-stopped

  node:
    build:
      context: node
    deploy:
      replicas: 0
    networks:
      - main
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: unless-stopped

  producer:
    build:
      context: producer
    networks:
      - main
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v${PROMETHEUS_VERSION}
    networks:
      - main
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    restart: unless-stopped

  rabbit:
    build:
      context: rabbit
    networks:
      - main
    ports:
      - 15672:15672
    restart: unless-stopped

  receiver:
    build:
      context: receiver
    deploy:
      replicas: 3
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${RECEIVER_PORT}/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped

  redis:
    image: redis:7.2.4-alpine3.19
    networks:
      - main
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - redis:/data

  redis_insight:
    depends_on:
      - redis
    image: redislabs/redisinsight:1.14.0
    networks:
      - main
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    restart: unless-stopped
    volumes:
      - redis_insight:/db

  redis_slave:
    command: redis-server --slaveof redis ${REDIS_PORT}
    image: redis:7.2.4-alpine3.19
    networks:
      - main
    ports:
      - 6380:6379
    restart: unless-stopped
    volumes:
      - redis_slave:/data

  statsd_exporter:
    image: prom/statsd-exporter:v${STATSD_EXPORTER_VERSION}
    networks:
      - main
    ports:
      - ${STATSD_EXPORTER_PORT}:${STATSD_EXPORTER_PORT}
    restart: unless-stopped

volumes:
  chronograf:
  cockroach_1:
  cockroach_2:
  cockroach_3:
  grafana_etc:
  grafana_var_lib:
  influx:
  mongo:
  nakama:
  postgres:
  redis:
  redis_insight:
  redis_slave:
