apiVersion: v1
kind: Pod
metadata:
  name: rabbit-1
  labels:
    app: rabbit-1
spec:
  volumes:
    - name: rabbit-1-claim
      persistentVolumeClaim:
        claimName: rabbit-1-claim
  containers:
    - name: rabbit
      image: registry.com.gecko/rabbit
      imagePullPolicy: Always
      ports:
        - containerPort: 5672
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/var/lib/rabbitmq/mnesia"
          name: rabbit-1-claim
