apiVersion: v1
kind: Pod
metadata:
  name: rabbit-1
  labels:
    app: rabbit-1
spec:
  volumes:
    - name: rabbit-1-claim
      persistentVolumeClaim:
        claimName: rabbit-1-claim
  containers:
    - name: rabbit
      image: registry.com.gecko/rabbit
      imagePullPolicy: Always
      env:
        - name: RABBITMQ_DEFAULT_PASS
          value: "go_password"
        - name: RABBITMQ_DEFAULT_USER
          value: "go_user"
        - name: RABBITMQ_NODE_PORT
          value: "5672"
      ports:
        - containerPort: 5672
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/var/lib/rabbitmq/mnesia"
          name: rabbit-1-claim
