apiVersion: v1
kind: Pod
metadata:
  name: roach-1
  labels:
    app: roach-1
spec:
  volumes:
    - name: roach-certs-claim
      persistentVolumeClaim:
        claimName: roach-certs-claim
    - name: roach-1-claim
      persistentVolumeClaim:
        claimName: roach-1-claim
  containers:
    - name: roach
      image: registry.com.gecko/roach
      imagePullPolicy: Always
      command: ["cockroach"]
      args: ["start-single-node", "--certs-dir=/certs/node-1"]
      ports:
        - containerPort: 26257
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/certs"
          name: roach-certs-claim
        - mountPath: "/cockroach/cockroach-data"
          name: roach-1-claim
