apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nakama
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - nakama.com.gecko
      secretName: stack-tls
  rules:
    - host: nakama.com.gecko
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nakama
                port:
                  number: 7351
