apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roach
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - roach.com.gecko
      secretName: stack-tls
  rules:
    - host: roach.com.gecko
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roach-1
                port:
                  number: 8080
