apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: certs-volume
