apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.70
    path: "/mnt/nfs_share/influx"
