apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: mongo-volume
