apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-1-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: rabbit-1-volume
