apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-1-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.com.gecko
    path: "/rabbit-1"
