kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: roach-certs-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
