apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roach-1-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: roach-1-volume
