kind: PersistentVolume
apiVersion: v1
metadata:
  name: roach-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/d/work/mnt/data"
