apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roach-certs-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: roach-certs-volume
