apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - rabbit.com.gecko
      secretName: src-tls
  rules:
    - host: rabbit.com.gecko
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbit-1
                port:
                  number: 15672
