apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: registry.com.gecko/api
        env:
          - name: COCKROACH_USER
            value: "a"
          - name: COCKROACH_PASSWORD
            value: "b"
          - name: COCKROACH_HOST
            value: "cockroachdb-public"
          - name: COCKROACH_PORT
            value: "26257"
          - name: COCKROACH_DATABASE
            value: "c"
        ports:
        - containerPort: 6000
