version: '3.9'

networks:
  main:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.200.0/24

services:
  bind9:
    build:
      context: bind9
    environment:
      - TZ=UTC
    networks:
      main:
        ipv4_address: 192.168.200.10
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: unless-stopped

  nginx:
    build:
      context: nginx
    networks:
      main:
        ipv4_address: 192.168.200.20
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - demo-certs:/certs

  jenkins:
    build:
      context: jenkins
    networks:
      main:
        ipv4_address: 192.168.200.30
    restart: unless-stopped
    volumes:
      - jenkins:/var/jenkins_home

  registry:
    environment:
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=[https://registry-ui.com.gecko]
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    image: registry:2.8.3
    networks:
      main:
        ipv4_address: 192.168.200.40
    restart: unless-stopped
    volumes:
      - registry:/registry-data

  registry-ui:
    environment:
      - DELETE_IMAGES=true
      - NGINX_PROXY_PASS_URL=http://192.168.200.40:5000
      - SHOW_CATALOG_NB_TAGS=true
      - SHOW_CONTENT_DIGEST=true
    image: joxit/docker-registry-ui:2.5.7-debian
    networks:
      main:
        ipv4_address: 192.168.200.50
    restart: unless-stopped
    volumes:
      - registry:/registry-data

volumes:
  demo-certs:
    external: true

  jenkins:
  registry:
