apiVersion: v1
kind: Pod
metadata:
  name: influx
  labels:
    app: influx
spec:
  volumes:
    - name: influx-claim
      persistentVolumeClaim:
        claimName: influx-claim
  containers:
    - name: influx
      image: registry.com.gecko/influx
      imagePullPolicy: Always
      env:
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "my-super-secret-auth-token"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "house"
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "my-org"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "go_password"
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: "1w"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "go_user"
      ports:
        - containerPort: 8086
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/var/lib/influxdb2"
          name: influx-claim
