CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE vehicles (
    id UUID PRIMARY KEY NOT NULL,
    plate VARCHAR NOT NULL,
    brand VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    year INT NOT NULL
);
