apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: localhost:5000/receiver
        ports:
        - containerPort: 7000
