apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: roach-certs-claim
          persistentVolumeClaim:
            claimName: roach-certs-claim
      containers:
        - name: api
          image: registry.com.gecko/api
          imagePullPolicy: Always
          env:
            - name: ROACH_DATABASE
              value: "go_demo"
            - name: ROACH_HOST
              value: "roach-service"
            - name: ROACH_PASSWORD
              value: "go_password"
            - name: ROACH_PORT
              value: "26257"
            - name: ROACH_USER
              value: "go_user"
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: "/certs"
              name: roach-certs-claim
