apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: registry.com.gecko/consumer
          imagePullPolicy: Always
          env:
            - name: RABBIT_HOST
              value: "rabbit-1"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
