apiVersion: apps/v1
kind: Deployment
metadata:
  name: roach-deployment
  labels:
    app: roach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roach
  template:
    metadata:
      labels:
        app: roach
    spec:
      containers:
      - name: roach
        image: registry.com.gecko/roach
        command: ["cockroach"]
        args: ["start-single-node", "--certs-dir=/certs"]
        imagePullPolicy: Always
        ports:
        - containerPort: 26257
        volumeMounts:
        - mountPath: "/certs"
          name: roach-certs-volume
        - mountPath: "/cockroach/cockroach-data"
          name: roach-volume
      volumes:
      - name: roach-certs-volume
        persistentVolumeClaim:
          claimName: roach-certs-volume-claim
      - name: roach-volume
        persistentVolumeClaim:
          claimName: roach-volume-claim
