version: '3.9'

networks:
  main:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.110.0/24

services:
  aggregator:
    build:
      context: ../../stack/services
      dockerfile: services/aggregator/Dockerfile
    env_file:
      - .env
    image: registry.com.gecko/aggregator
    networks:
      - main
    restart: unless-stopped
    volumes:
      - demo-roach-certs:/certs

  api:
    build:
      context: ../../stack/services
      dockerfile: services/api/Dockerfile
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/api
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:6000/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped
    volumes:
      - demo-roach-certs:/certs

  consumer:
    build:
      context: ../../stack/services
      dockerfile: services/consumer/Dockerfile
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/consumer
    networks:
      - main
    restart: unless-stopped

  grafana:
    build:
      context: ../../stack/grafana
    image: registry.com.gecko/grafana
    networks:
      - main
    restart: unless-stopped
    volumes:
      - grafana-etc:/etc/grafana
      - grafana-var-lib:/var/lib/grafana

  haproxy:
    build:
      context: ../../stack/haproxy
    image: registry.com.gecko/haproxy
    networks:
      - main
    restart: unless-stopped

  influx:
    build:
      context: ../../stack/influx
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_BUCKET=house
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${INFLUX_PORT}/ping"]
      interval: 10s
      timeout: 2s
      retries: 2
    image: registry.com.gecko/influx
    networks:
      - main
    restart: unless-stopped
    volumes:
      - influx:/var/lib/influxdb2

  mongo:
    build:
      context: ../../stack/mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    image: registry.com.gecko/mongo
    networks:
      - main
    restart: unless-stopped
    volumes:
      - mongo:/data/db

  mongo-express:
    build:
      context: ../../stack/mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    image: registry.com.gecko/mongo-express
    networks:
      - main
    restart: unless-stopped

  nakama:
    build:
      context: ../../stack/nakama
    image: registry.com.gecko/nakama
    networks:
      - main
    restart: unless-stopped
    volumes:
      - demo-roach-certs:/certs
      - nakama:/nakama/data

  node:
    build:
      context: ../../stack/node
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/node
    networks:
      - main
    restart: unless-stopped

  node-exporter:
    build:
      context: ../../stack/node-exporter
    image: registry.com.gecko/node-exporter
    networks:
      - main
    restart: unless-stopped

  nginx:
    build:
      context: ../../stack/nginx
    image: registry.com.gecko/nginx
    networks:
      - main
    ports:
      - 4000:443
    restart: unless-stopped
    volumes:
      - demo-certs:/certs

  pistache:
    build:
      context: ../../stack/pistache
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/pistache
    networks:
      - main
    restart: unless-stopped

  producer:
    build:
      context: ../../stack/services
      dockerfile: services/producer/Dockerfile
    env_file:
      - .env
    image: registry.com.gecko/producer
    networks:
      - main
    restart: unless-stopped
    volumes:
      - demo-certs:/certs

  prometheus:
    build:
      context: ../../stack/prometheus
    image: registry.com.gecko/prometheus
    networks:
      - main
    restart: unless-stopped

  python:
    build:
      context: ../../stack/python
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/python
    networks:
      - main
    restart: unless-stopped

  rabbit-1:
    build:
      context: ../../stack/rabbit
    image: registry.com.gecko/rabbit
    networks:
      - main
    restart: unless-stopped
    volumes:
      - rabbit-1:/var/lib/rabbitmq/mnesia

  rabbit-2:
    build:
      context: ../../stack/rabbit
    image: registry.com.gecko/rabbit
    networks:
      - main
    restart: unless-stopped
    volumes:
      - rabbit-2:/var/lib/rabbitmq/mnesia

  rabbit-3:
    build:
      context: ../../stack/rabbit
    image: registry.com.gecko/rabbit
    networks:
      - main
    restart: unless-stopped
    volumes:
      - rabbit-3:/var/lib/rabbitmq/mnesia

  receiver:
    build:
      context: ../../stack/services
      dockerfile: services/receiver/Dockerfile
    deploy:
      replicas: 3
    env_file:
      - .env
    image: registry.com.gecko/receiver
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7000/v1/healthcheck']
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - main
    restart: unless-stopped

  redis-1:
    build:
      context: ../../stack/redis
    image: registry.com.gecko/redis
    networks:
      - main
    restart: unless-stopped
    volumes:
      - redis-1:/data

  redis-2:
    build:
      context: ../../stack/redis
    environment:
      - MASTER_HOST=redis-1
      - MASTER_PORT=6379
    image: registry.com.gecko/redis
    networks:
      - main
    restart: unless-stopped
    volumes:
      - redis-2:/data

  redis-3:
    build:
      context: ../../stack/redis
    environment:
      - MASTER_HOST=redis-1
      - MASTER_PORT=6379
    image: registry.com.gecko/redis
    networks:
      - main
    restart: unless-stopped
    volumes:
      - redis-3:/data

  redis-insight:
    build:
      context: ../../stack/redis-insight
    image: registry.com.gecko/redis-insight
    networks:
      - main
    restart: unless-stopped
    volumes:
      - redis-insight:/db

  roach-1:
    build:
      context: ../../stack/roach
    command: start --advertise-addr=roach-1:26357 --certs-dir=/certs/node-1 --http-addr=roach-1:8080 --listen-addr=roach-1:26357 --sql-addr=roach-1:26257 --join=roach-1:26357,roach-2:26357,roach-3:26357
    image: registry.com.gecko/roach
    networks:
      - main
    restart: unless-stopped
    volumes:
      - roach-1:/cockroach/cockroach-data
      - demo-roach-certs:/certs

  roach-2:
    build:
      context: ../../stack/roach
    command: start --advertise-addr=roach-2:26357 --certs-dir=/certs/node-2 --http-addr=roach-2:8081 --listen-addr=roach-2:26357 --sql-addr=roach-2:26258 --join=roach-1:26357,roach-2:26357,roach-3:26357
    image: registry.com.gecko/roach
    networks:
      - main
    restart: unless-stopped
    volumes:
      - roach-2:/cockroach/cockroach-data
      - demo-roach-certs:/certs

  roach-3:
    build:
      context: ../../stack/roach
    command: start --advertise-addr=roach-3:26357 --certs-dir=/certs/node-3 --http-addr=roach-3:8082 --listen-addr=roach-3:26357 --sql-addr=roach-3:26259 --join=roach-1:26357,roach-2:26357,roach-3:26357
    image: registry.com.gecko/roach
    networks:
      - main
    restart: unless-stopped
    volumes:
      - roach-3:/cockroach/cockroach-data
      - demo-roach-certs:/certs

  statsd-exporter:
    build:
      context: ../../stack/statsd-exporter
    image: registry.com.gecko/statsd-exporter
    networks:
      - main
    restart: unless-stopped

volumes:
  demo-certs:
    external: true
  demo-roach-certs:
    external: true

  roach-1:
  roach-2:
  roach-3:
  dynamodb:
  grafana-etc:
  grafana-var-lib:
  influx:
  mongo:
  nakama:
  rabbit-1:
  rabbit-2:
  rabbit-3:
  redis-1:
  redis-2:
  redis-3:
  redis-insight:
