pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'stack/build.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh 'stack/run.sh'
            }
        }
    }
}
